### ISSUE TITLE
Notice: Undefined index in reviews

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#323]
`Notice: Undefined index: publishpress-checklists in /path/to/wordpress/wp-content/plugins/publishpress-checklists/vendor/publishpress/wordpress-reviews/ReviewsController.php on line 419`

**Comment by olatechpro** [comment]
@stevejburge this issue is review library related and not checklists although it may have been fixed already as i'm not getting the undefined index report in my debug log.

**Comment by andergmartins** [comment]
I just updated the Reviews library, and can't replicate the bug. But I was not able to replicate it before as well, so still can't confirm it is a real fix. Lets keep this open and investigate this a little more for the next release.

**Comment by olatechpro** [comment]
Fixed
