### ISSUE TITLE
Conflict with RankMath

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Checklists#566]
When RankMath activated, sometime the checklist is not realtime.

Step to replicate: 

1. Create new checklist
2. Number of word in content
3. Create new post
4. Add some content so it satisfy the checklist
5. Publish
6. After refresh, you will not be able to update the post because the checklist is cross (X)
7. It will green only if you edit the content again. 

Check this video for better explanation: https://www.loom.com/share/c1b95890613a42e7bcdb36100ef546bf

**Comment by olatechpro** [comment]
Fixed

**Comment by rizaardiyanto1412** [comment]
Reopen this because the issue persists

https://www.loom.com/share/b1c8ffb16d1147298003ab9a27ec3570

https://wordpress.org/support/topic/plugin-causes-conflict-with-with-rankmath/

**Comment by olatechpro** [comment]
@rizaardiyanto1412 I closed this 2 weeks ago and sent you a package to test. Although it's yet to be released but you can test again when you get another package tomorrow

**Comment by rizaardiyanto1412** [comment]
@olatechpro Ah sorry Ola. I thought the one that I tested is already released
